num_a=float(input('Enter a number: '))
num_b=float(input('Enter a number: '))
print('\nThanks folks: ',num_a + num_b)
print('-------------------------------')
num_a=float(input('Enter a number: '))
num_b=float(input('Enter a number: '))
print('\nThanks folks:: ',num_a - num_b)
print('-------------------------------')
num_a=float(input('Enter a number: '))
num_b=float(input('Enter a number: '))
print('\nThanks folks:: ',num_a * num_b)
print('-------------------------------')
num_a=float(input('Enter a number: '))
num_b=float(input('Enter a number: '))
print('\nThanks folks:: ',num_a / num_b)

